POST http://localhost:8080/api/ingest
Content-Type: application/json

{
    "collection":"banks_collection",
    "urls": [
        "https://www.fdic.gov/system/files/2024-07/banklist.csv"
    ]
}

###

POST http://localhost:8080/api/chat
Content-Type: application/json

{
    "collection": "FAQ",
    "messages": [
        {
            "role": "user",
            "content": "What is the speed of light?"
        }
    ],
    "max_tokens": 100,
    "temperature": 0.1
}

###

POST http://localhost:8080/api/query
Content-Type: application/json

{
    "collection": "FAQ",
    "query": "What is the return policy?",
    "limit": 3,
    "relevance": 0.75
}

###

POST http://localhost:11434/v1/chat/completions
Content-Type: application/json

{
        "model": "llama3",
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "What is the speed of light?"
            }
        ],
        "max_tokens": 100,
        "temperature": 0.1,
        "stream":false
}

###

POST http://localhost:11434/v1/embeddings
Content-Type: application/json

{
        "model": "nomic-embed-text",
        "input": "The speed of light is 300,000 km/s."
}

